"""initialize tables

Revision ID: 3e1f0c7a5312
Revises:
Create Date: 2026-03-26 11:03:48.177119

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "3e1f0c7a5312"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.Column("additional_info", sa.String(length=63), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "temperatures",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "date_time",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("temperature", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("city_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["city_id"],
            ["cities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("temperatures")
    op.drop_table("cities")
    # ### end Alembic commands ###
